# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import server_pb2 as server__pb2


class NlpServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CorrectGrammar = channel.unary_unary(
                '/proto.NlpServer/CorrectGrammar',
                request_serializer=server__pb2.CorrectGrammarRequest.SerializeToString,
                response_deserializer=server__pb2.CorrectGrammarResponse.FromString,
                )


class NlpServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CorrectGrammar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NlpServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CorrectGrammar': grpc.unary_unary_rpc_method_handler(
                    servicer.CorrectGrammar,
                    request_deserializer=server__pb2.CorrectGrammarRequest.FromString,
                    response_serializer=server__pb2.CorrectGrammarResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.NlpServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NlpServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CorrectGrammar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.NlpServer/CorrectGrammar',
            server__pb2.CorrectGrammarRequest.SerializeToString,
            server__pb2.CorrectGrammarResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
