// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: server.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NlpServerClient is the client API for NlpServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NlpServerClient interface {
	CorrectGrammar(ctx context.Context, in *CorrectGrammarRequest, opts ...grpc.CallOption) (*CorrectGrammarResponse, error)
}

type nlpServerClient struct {
	cc grpc.ClientConnInterface
}

func NewNlpServerClient(cc grpc.ClientConnInterface) NlpServerClient {
	return &nlpServerClient{cc}
}

func (c *nlpServerClient) CorrectGrammar(ctx context.Context, in *CorrectGrammarRequest, opts ...grpc.CallOption) (*CorrectGrammarResponse, error) {
	out := new(CorrectGrammarResponse)
	err := c.cc.Invoke(ctx, "/proto.NlpServer/CorrectGrammar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NlpServerServer is the server API for NlpServer service.
// All implementations must embed UnimplementedNlpServerServer
// for forward compatibility
type NlpServerServer interface {
	CorrectGrammar(context.Context, *CorrectGrammarRequest) (*CorrectGrammarResponse, error)
	mustEmbedUnimplementedNlpServerServer()
}

// UnimplementedNlpServerServer must be embedded to have forward compatible implementations.
type UnimplementedNlpServerServer struct {
}

func (UnimplementedNlpServerServer) CorrectGrammar(context.Context, *CorrectGrammarRequest) (*CorrectGrammarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CorrectGrammar not implemented")
}
func (UnimplementedNlpServerServer) mustEmbedUnimplementedNlpServerServer() {}

// UnsafeNlpServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NlpServerServer will
// result in compilation errors.
type UnsafeNlpServerServer interface {
	mustEmbedUnimplementedNlpServerServer()
}

func RegisterNlpServerServer(s grpc.ServiceRegistrar, srv NlpServerServer) {
	s.RegisterService(&NlpServer_ServiceDesc, srv)
}

func _NlpServer_CorrectGrammar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CorrectGrammarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NlpServerServer).CorrectGrammar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NlpServer/CorrectGrammar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NlpServerServer).CorrectGrammar(ctx, req.(*CorrectGrammarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NlpServer_ServiceDesc is the grpc.ServiceDesc for NlpServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NlpServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.NlpServer",
	HandlerType: (*NlpServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CorrectGrammar",
			Handler:    _NlpServer_CorrectGrammar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
